[phases.setup]
aptPkgs = [
  "libglib2.0-0",
  "libdbus-1-3",
  "libnss3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libexpat1",
  "libxkbcommon0",
  "libasound2",
  "libnspr4",
  "libgbm1",
  "libcups2",
  "libdrm2",
  "libxcb1",
  "libxcomposite1",
  "libxdamage1",
  "libxext6",
  "libxfixes3",
  "libxrandr2",
  "libpango-1.0-0",
  "libcairo2"
]

[variables]
PLAYWRIGHT_BROWSERS_PATH = "/app/.cache/ms-playwright"

[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "PLAYWRIGHT_BROWSERS_PATH=/app/.cache/ms-playwright playwright install chromium"
]
